<?php


namespace app\models;


use yii\base\Model;

class RegisterForm extends Model
{

    public $inn;
    public $password;
    public $rePassword;
    public $contract;
    public $email;
    public $phone;
    public $method;
    public $kpp;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['inn', 'contract', 'password', 'rePassword'], 'required'],
            ['rePassword', 'compare', 'compareAttribute' => 'password'],
            ['email', 'email'],
            [['phone', 'method', 'kpp'], 'trim'],
            //[['phone','email'], 'unique', 'targetClass'=>'app/models/User'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'inn'=>'ИНН',
            'contract'=>'Договор',
            'password'=>'Пароль',
            'rePassword'=>'Повторите пароль',
            'email'=>'E-mail',
            'phone'=>'Телефон',
        ]; // TODO: Change the autogenerated stub
    }

    public function Registr(){
        $user = new User();
        if (!empty($this->kpp)){
            $user->username = $this->inn.'-'.$this->kpp;
        } else {
            $user->username = $this->inn;
        }
        if (!empty($user->username)){
            $user->email = $this->email;
            $user->phone = $this->phone;
            $user->inn = $this->inn;
            $user->contract = $this->contract;
            $user->kpp = $this->kpp;
            $user->setPassword($this->password);
            $user->generateAuthKey();
            $user->setIdDb();
            $validate = $user->validateFromDB($this->method);

            if ($validate['success']){
                if ($user->save()){
                    return ['uName'=>$user->username];
                } else {
                    return ['error'=>'Не удалось зарегистрироваться - повторите попытку пзже.'];
                }
            } else {
                return ['error'=> $validate['error']];
            }

        }
    }
}