<?php


namespace app\models;


use yii\base\Model;
use Yii;

class VerificationForm extends Model
{
    public $code;

    private $_user = false;

    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            ['code', 'validateCode'],
        ];
    }

    public function attributeLabels()
    {
        return ['code' => 'Код подтверждения']; // TODO: Change the autogenerated stub
    }

    public function validateCode($attribute, $params)
    {
        if (!$this->hasErrors()) {
            if ($this->code != Yii::$app->session->get('vCode')) {
                $this->addError($attribute, 'Неверно введён код');
            }
        }
    }

    public function activate()
    {
        if ($this->validate()) {
            $user = User::findOne(['id' => Yii::$app->session->get('uId')]);
            if ($result = $user->activation() === true){
                return ['uName' => $user->username];
            } else {
                return $result;
            }
        }
        return false;
    }


}