<?php


namespace app\models;


use yii\base\Model;
use Yii;

class VerificationForm extends Model
{
    public $code;

    private $_user = false;

    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            ['code', 'validateCode'],
            ['code', 'required'],
        ];
    }

    public function attributeLabels()
    {
        return ['code' => 'Код подтверждения']; // TODO: Change the autogenerated stub
    }

    public function validateCode($attribute, $params)
    {
         Yii::error('Это начало валидэйт код \n');
        if (!$this->hasErrors()) {
            
         Yii::error('нет до этого ошибок валидэйт код \n');
            if ($this->code != Yii::$app->session->get('vCode')) {
                
         Yii::error('невалиден код \n');
                $this->addError($attribute, 'Неверно введён код');
            }
        }
    }

    public function activate()
    {
        
         Yii::error('Это начало активэйт код \n');
        if ($this->validate()) {
            
         Yii::error('прошло валидэйт \n');
            $user = User::findOne(['id' => Yii::$app->session->get('uId')]);
            
         Yii::error('Искали юзера \n');
            if ($result = $user->activation() === true){
                
         Yii::error('нашли \n');
                return ['uName' => $user->username];
            } else {
                
         Yii::error('не нашли \n');
                return $result;
            }
        }
        return false;
    }


}